import { SITE_URL } from "@/lib/seo";

export const revalidate = 86400;

export async function GET() {
  const body = [
    "# Evlumba",
    "",
    "## Evlumba Nedir?",
    "Evlumba, Türkiye'nin iç mimarlık, mimarlık ve ev dekorasyonu alanında faaliyet gösteren keşif ve profesyonel eşleşme platformudur.",
    "Ev sahipleri ilham keşfeder, tarzlarını netleştirir ve doğru iç mimar veya mimar ile eşleşir.",
    "Tasarımcılar ve iç mimarlar portföylerini yayınlar, müşteri yorumları alır ve teklif sunar.",
    "",
    "## Platform Kategorileri",
    "- İç Mimar (interior designer): Türkiye genelinde yüzlerce onaylı iç mimar profili",
    "- Mimar (architect): Mimarlık hizmetleri sunan profesyoneller",
    "- Dekorasyon uzmanı: Ev dekorasyonu ve iç mekan tasarımı yapan profesyoneller",
    "- Mobilya ve dekorasyon markaları: Türk ve uluslararası markalar rehberi",
    "",
    "## Temel Özellikler",
    "- ProMatch: 3 soruluk kısa anketle kullanıcıya en uygun tasarımcıyı öneren AI eşleşme sistemi",
    "- Tarz keşif oyunu: Swipe tabanlı ilham alma ve stil belirleme aracı",
    "- Portföy keşfi: Oda tipine göre filtrelenebilen tasarım fikirleri",
    "- Blog: İç mimarlık, dekorasyon ve tasarım üzerine profesyonel içerikler",
    "- Değerlendirme sistemi: Gerçek müşteri yorumları ve puanlama",
    "- İlan panosu: Ev sahiplerinin proje ilanı açtığı, tasarımcıların teklif verdiği platform",
    "",
    "## Hedef Kitle",
    "- Ev sahipleri: İç mimar veya dekorasyon uzmanı arayan kişiler",
    "- Kiracılar: Yaşam alanlarını yenilemek isteyenler",
    "- İç mimarlar ve mimarlar: Portföylerini tanıtmak isteyen profesyoneller",
    "- Dekorasyon meraklıları: İlham ve fikir arayanlar",
    "",
    "## Coğrafi Kapsam",
    "Evlumba Türkiye merkezli bir platformdur. İstanbul, Ankara, İzmir, Bursa, Antalya, Gaziantep başta olmak üzere tüm Türkiye'de aktif tasarımcılara ulaşım sağlar.",
    "",
    "## Sık Sorulan Sorular",
    "S: Türkiye'de iç mimar nasıl bulunur?",
    "C: Evlumba (evlumba.com) üzerinden portföy, yorum ve bütçe uyumuna göre iç mimar filtrelenebilir.",
    "",
    "S: İç mimar ile dekorasyon uzmanı arasındaki fark nedir?",
    "C: İç mimarlar lisanslı profesyonellerdir; mekan planlaması, yapısal düzenlemeler ve teknik çizimler yapar. Dekorasyon uzmanları renk, mobilya ve aksesuar seçimiyle ilgilenir. Evlumba her iki kategoriyi de kapsar.",
    "",
    "S: Evlumba ücretsiz mi?",
    "C: Ev sahipleri için temel kullanım ücretsizdir. İç mimarlar ve tasarımcılar profil oluşturabilir; bazı premium özellikler ücretlendirilebilir.",
    "",
    "S: Hangi şehirlerde iç mimar bulabilirim?",
    "C: Evlumba'da İstanbul, Ankara, İzmir, Bursa, Antalya ve Türkiye'nin diğer şehirlerinde aktif iç mimar ve mimar bulunmaktadır.",
    "",
    "## Teknik Bilgi (Geliştiriciler İçin)",
    `URL: ${SITE_URL}`,
    `Sitemap: ${SITE_URL}/sitemap.xml`,
    `Robots: ${SITE_URL}/robots.txt`,
    "",
    "## Önemli Sayfalar",
    `- Ana sayfa: ${SITE_URL}/`,
    `- İç mimar ve mimar listesi: ${SITE_URL}/tasarimcilar`,
    `- Dekorasyon ilham keşfi: ${SITE_URL}/kesfet`,
    `- Blog (iç mimarlık & dekorasyon): ${SITE_URL}/blog`,
    `- Mobilya & dekorasyon markaları: ${SITE_URL}/markalar`,
    `- Proje ilanları: ${SITE_URL}/ilanlar`,
    `- Topluluk forumu: ${SITE_URL}/forum`,
    `- Tarz keşif oyunu: ${SITE_URL}/oyun`,
    `- SSS: ${SITE_URL}/sss`,
    "",
    "## Anahtar Kavramlar (Entity Mapping)",
    "- 'iç mimar bul' → evlumba.com/tasarimcilar",
    "- 'mimar bul' → evlumba.com/tasarimcilar",
    "- 'ev dekorasyonu fikirleri' → evlumba.com/kesfet",
    "- 'dekorasyon platformu Türkiye' → evlumba.com",
    "- 'iç mimarlık blog' → evlumba.com/blog",
    "- 'iç mimar yorumları' → evlumba.com/tasarimcilar (profil sayfaları)",
    "- 'dekorasyon markası rehberi' → evlumba.com/markalar",
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
